"""Unit tests for dependency parsers."""

import json
import tempfile
from pathlib import Path

from localguard.auditors.sca.parsers import ComposerParser, NPMParser, PipParser
from localguard.auditors.sca.sources.offline import OfflineCVESource


class TestComposerParser:
    """Tests for ComposerParser."""

    def setup_method(self):
        self.parser = ComposerParser()

    def test_parse_composer_lock(self):
        """Test parsing composer.lock file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_file = Path(tmpdir) / "composer.lock"
            lock_data = {
                "packages": [
                    {
                        "name": "laravel/framework",
                        "version": "v10.10.0",
                        "description": "The Laravel Framework.",
                    },
                    {
                        "name": "symfony/console",
                        "version": "v6.2.8",
                        "description": "Symfony Console Component",
                    },
                ],
                "packages-dev": [
                    {
                        "name": "phpunit/phpunit",
                        "version": "10.5.0",
                        "description": "PHPUnit testing framework",
                    }
                ],
            }
            lock_file.write_text(json.dumps(lock_data))

            deps = self.parser.parse(lock_file)
            assert len(deps) == 3

            # Check production deps
            prod_deps = [d for d in deps if not d.dev]
            assert len(prod_deps) == 2

            # Check dev deps
            dev_deps = [d for d in deps if d.dev]
            assert len(dev_deps) == 1
            assert dev_deps[0].name == "phpunit/phpunit"

    def test_parse_composer_lock_missing_version(self):
        """Test handling of packages without version."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_path = Path(tmpdir) / "composer.lock"
            lock_data = {"packages": [{"name": "test/package"}]}  # No version
            lock_path.write_text(json.dumps(lock_data))

            deps = self.parser.parse(lock_path)
            assert len(deps) == 0  # Should skip packages without version

    def test_get_lock_files(self):
        """Test finding composer.lock files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            # Create nested structure
            lock1 = Path(tmpdir) / "composer.lock"
            lock1.write_text("{}")
            subdir = Path(tmpdir) / "subdir"
            subdir.mkdir(parents=True, exist_ok=True)
            lock2 = subdir / "composer.lock"
            lock2.write_text("{}")

            files = self.parser.get_lock_files(Path(tmpdir))
            assert len(files) == 2


class TestNPMParser:
    """Tests for NPMParser."""

    def setup_method(self):
        self.parser = NPMParser()

    def test_parse_package_lock_v2(self):
        """Test parsing package-lock.json v2/v3 format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_file = Path(tmpdir) / "package-lock.json"
            lock_data = {
                "lockfileVersion": 2,
                "packages": {
                    "": {"version": "1.0.0"},
                    "node_modules/lodash": {"version": "4.17.21", "license": "MIT"},
                    "node_modules/express": {"version": "4.18.2", "license": "MIT"},
                },
            }
            lock_file.write_text(json.dumps(lock_data))

            deps = self.parser.parse(lock_file)
            assert len(deps) == 2
            assert all(d.ecosystem == "npm" for d in deps)

    def test_parse_package_lock_v1(self):
        """Test parsing package-lock.json v1 format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_file = Path(tmpdir) / "package-lock.json"
            lock_data = {
                "lockfileVersion": 1,
                "dependencies": {
                    "lodash": {"version": "4.17.21", "dev": False},
                    "express": {"version": "4.18.2", "dev": False},
                },
            }
            lock_file.write_text(json.dumps(lock_data))

            deps = self.parser.parse(lock_file)
            assert len(deps) == 2

    def test_parse_yarn_lock(self):
        """Test parsing yarn.lock file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_file = Path(tmpdir) / "yarn.lock"
            lock_content = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
"""
            lock_file.write_text(lock_content)

            deps = self.parser.parse(lock_file)
            # yarn.lock parsing is basic, may not find all
            assert isinstance(deps, list)

    def test_get_lock_files(self):
        """Test finding package-lock.json and yarn.lock files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            (Path(tmpdir) / "package-lock.json").write_text("{}")
            (Path(tmpdir) / "yarn.lock").write_text("")

            files = self.parser.get_lock_files(Path(tmpdir))
            assert len(files) == 2


class TestPipParser:
    """Tests for PipParser."""

    def setup_method(self):
        self.parser = PipParser()

    def test_parse_requirements_txt(self):
        """Test parsing requirements.txt."""
        with tempfile.TemporaryDirectory() as tmpdir:
            req_file = Path(tmpdir) / "requirements.txt"
            req_file.write_text("""
django==4.2.10
requests>=2.28.0
flask~=2.3.0
# This is a comment
numpy==1.24.3
""")

            deps = self.parser.parse(req_file)
            assert len(deps) == 4
            assert all(d.ecosystem == "pip" for d in deps)

            # Check specific versions
            django = next(d for d in deps if d.name == "django")
            assert django.version == "4.2.10"

    def test_parse_pyproject_toml_pep621(self):
        """Test parsing pyproject.toml with PEP 621 dependencies."""
        with tempfile.TemporaryDirectory() as tmpdir:
            pyproject_file = Path(tmpdir) / "pyproject.toml"
            pyproject_file.write_text("""
[project]
name = "test-project"
version = "1.0.0"
dependencies = [
    "requests>=2.28.0",
    "click>=8.0.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.0.0", "black>=23.0.0"]
""")

            deps = self.parser.parse(pyproject_file)
            assert len(deps) == 4  # 2 main + 2 optional

            # Check dev dependencies are marked
            dev_deps = [d for d in deps if d.dev]
            assert len(dev_deps) == 2

    def test_parse_poetry_lock(self):
        """Test parsing poetry.lock."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_file = Path(tmpdir) / "poetry.lock"
            lock_content = """
[package]
name = "requests"
version = "2.28.1"
category = "main"

[package]
name = "pytest"
version = "7.4.0"
category = "dev"
"""
            lock_file.write_text(lock_content)

            deps = self.parser.parse(lock_file)
            assert len(deps) == 2

            pytest_dep = next(d for d in deps if d.name == "pytest")
            assert pytest_dep.dev is True

    def test_parse_pipfile_lock(self):
        """Test parsing Pipfile.lock."""
        with tempfile.TemporaryDirectory() as tmpdir:
            lock_file = Path(tmpdir) / "Pipfile.lock"
            lock_data = {
                "default": {
                    "requests": {"version": "==2.28.1"},
                },
                "develop": {
                    "pytest": {"version": "==7.4.0"},
                },
            }
            lock_file.write_text(json.dumps(lock_data))

            deps = self.parser.parse(lock_file)
            assert len(deps) == 2

            pytest_dep = next(d for d in deps if d.name == "pytest")
            assert pytest_dep.dev is True

    def test_parse_requirement_line_vcs(self):
        """Test parsing VCS requirement lines (should be skipped)."""
        from localguard.auditors.sca.parsers.pip import PipParser

        parser = PipParser()

        # Git URLs should be skipped
        dep = parser._parse_requirement_line("git+https://github.com/user/repo.git")
        assert dep is None

        dep = parser._parse_requirement_line("-e git+https://github.com/user/repo.git#egg=package")
        assert dep is None

    def test_get_lock_files(self):
        """Test finding Python dependency files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            (Path(tmpdir) / "requirements.txt").write_text("")
            (Path(tmpdir) / "requirements-dev.txt").write_text("")
            (Path(tmpdir) / "pyproject.toml").write_text("")
            (Path(tmpdir) / "poetry.lock").write_text("")
            (Path(tmpdir) / "Pipfile.lock").write_text("{}")

            files = self.parser.get_lock_files(Path(tmpdir))
            assert len(files) == 5


class TestOfflineCVESource:
    """Tests for OfflineCVESource."""

    def setup_method(self):
        self.cve_source = OfflineCVESource()

    def test_query_known_vulnerable_package(self):
        """Test querying known vulnerable package."""
        cves = self.cve_source.query("laravel/framework", "composer", "10.0.0")
        assert len(cves) > 0
        assert any(cve.cve_id == "CVE-2023-48217" for cve in cves)

    def test_query_safe_version(self):
        """Test querying safe version returns no CVEs."""
        cves = self.cve_source.query("laravel/framework", "composer", "10.10.0")
        assert len(cves) == 0

    def test_query_unknown_package(self):
        """Test querying unknown package returns empty."""
        cves = self.cve_source.query("unknown/package", "composer", "1.0.0")
        assert len(cves) == 0

    def test_query_npm_vulnerable(self):
        """Test querying vulnerable npm package."""
        cves = self.cve_source.query("lodash", "npm", "4.17.20")
        assert len(cves) > 0

    def test_query_pip_vulnerable(self):
        """Test querying vulnerable pip package."""
        cves = self.cve_source.query("django", "pip", "4.0.0")
        assert len(cves) > 0

    def test_get_all_cves(self):
        """Test getting all CVEs in database."""
        all_cves = self.cve_source.get_all_cves()
        assert len(all_cves) > 20  # Offline DB ships with ~24 entries
